# Generated by Django 2.2.10 on 2020-10-16 14:49

from django.db import migrations, models
import recipe_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=recipe_api.models.recipe_image_file_path),
        ),
    ]
